// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njhqxvyvnhngsumairnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qaHF4dnl2bmhuZ3N1bWFpcm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjQyODQsImV4cCI6MjA2NzA0MDI4NH0.CrtVG6JgM9wO4SuFHENNkATad2lZVi3Oi3E9wu82v-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});